### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by t-nakatani** [t-nakatani/CI_teamC#13]
# 公開までにすることリスト

### 必須事項

- [x] マウスオーバー時，翻訳後テキストの表示機能
- [x] translationモデルの事前読みこみ https://github.com/t-nakatani/CI_teamC/issues/14
  - [x] notebook環境の作成
- [x] https://github.com/t-nakatani/CI_teamC/issues/8
- [x] 表示ツイートの制限
  - [x] 件数 5つ(１行に収まる数)
  - [x] ~~高さ~~
- [x] **和歌山県を追加**

### 余裕があれば
- [x] AppConfig.ready()を利用したmodel_load
- [x] homeページのボタン配置変更
- [x] https://github.com/t-nakatani/CI_teamC/issues/12
- [x] グルメだけでなく観光なども検索できるように

**Comment by t-nakatani** [comment]
heightの項目がない，高さの制限は難しそう
https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/embedded-tweet-parameter-reference

**Comment by t-nakatani** [comment]
```
/usr/local/lib/python3.9/site-packages/transformers/models/marian/tokenization_marian.py:194: UserWarning: Recommended: pip install sacremoses.
```
trasnlationでwarning，要修正
* pip install sacremoses

**Comment by t-nakatani** [comment]
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/51512765/212952697-b96a60c3-1c9b-45b7-9449-ae0f70a1cb69.png">

**Comment by t-nakatani** [comment]
>AppConfig.ready()を利用したmodel_load

ざっと調べたところお行儀の良い書き方ではあるが，動作は現状と大きく変わらなそう．
時間もないので今回は作業対象外とする．

**Comment by t-nakatani** [comment]
All tasks have been completed！
